# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/ilpes/Desktop/INSEGNAMENTO/Didattica2023/McDMA/McDMA_v3/McDMA_v3.srcs/sources_1/bd/user_35t/ip/user_35t_xbar_4/user_35t_xbar_4.xci
# IP: The module: 'user_35t_xbar_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ilpes/Desktop/INSEGNAMENTO/Didattica2023/McDMA/McDMA_v3/McDMA_v3.srcs/sources_1/bd/user_35t/ip/user_35t_xbar_4/user_35t_xbar_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'user_35t_xbar_4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/ilpes/Desktop/INSEGNAMENTO/Didattica2023/McDMA/McDMA_v3/McDMA_v3.srcs/sources_1/bd/user_35t/ip/user_35t_xbar_4/user_35t_xbar_4.xci
# IP: The module: 'user_35t_xbar_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ilpes/Desktop/INSEGNAMENTO/Didattica2023/McDMA/McDMA_v3/McDMA_v3.srcs/sources_1/bd/user_35t/ip/user_35t_xbar_4/user_35t_xbar_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'user_35t_xbar_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
