webtalk_init -webtalk_dir C:/Users/ilpes/Downloads/Cmod-A7-35T-XADC-hw.xpr/hw/hw.sim/sim_1/behav/xsim/xsim.dir/XADCdemo_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Mar 30 22:54:02 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "175570403_179783142_210754068_723" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1e295a68-03a2-4243-81ab-332a92e09120" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5fa5fba16afb4dd7b3fccf68c143cba5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2803 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8668_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1446995347 -regid "175570403_179783142_210754068_723" -xml C:/Users/ilpes/Downloads/Cmod-A7-35T-XADC-hw.xpr/hw/hw.sim/sim_1/behav/xsim/xsim.dir/XADCdemo_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/ilpes/Downloads/Cmod-A7-35T-XADC-hw.xpr/hw/hw.sim/sim_1/behav/xsim/xsim.dir/XADCdemo_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/ilpes/Downloads/Cmod-A7-35T-XADC-hw.xpr/hw/hw.sim/sim_1/behav/xsim/xsim.dir/XADCdemo_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
