
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2025 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xtrafgen.h"

/*
* The configuration table for devices
*/

XTrafGen_Config XTrafGen_ConfigTable[] =
{
	{
		XPAR_XTRAFGEN_0_DEVICE_ID,
		XPAR_XTRAFGEN_0_BASEADDR,
		XPAR_XTRAFGEN_0_ATG_MODE,
		XPAR_XTRAFGEN_0_ATG_MODE_L2,
		XPAR_XTRAFGEN_0_AXIS_MODE,
		XPAR_XTRAFGEN_0_EXTENDED_ADDRESS_WIDTH
	}
};

