# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ilpes/Desktop/INSEGNAMENTO/Didattica2023/McDMA/McDMA_v5_int_edge/McDMA_v5_int_edge.srcs/sources_1/bd/user_35t/ip/user_35t_auto_us_3/user_35t_auto_us_3.xci
# IP: The module: 'user_35t_auto_us_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ilpes/Desktop/INSEGNAMENTO/Didattica2023/McDMA/McDMA_v5_int_edge/McDMA_v5_int_edge.srcs/sources_1/bd/user_35t/ip/user_35t_auto_us_3/user_35t_auto_us_3_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'user_35t_auto_us_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ilpes/Desktop/INSEGNAMENTO/Didattica2023/McDMA/McDMA_v5_int_edge/McDMA_v5_int_edge.srcs/sources_1/bd/user_35t/ip/user_35t_auto_us_3/user_35t_auto_us_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'user_35t_auto_us_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/ilpes/Desktop/INSEGNAMENTO/Didattica2023/McDMA/McDMA_v5_int_edge/McDMA_v5_int_edge.srcs/sources_1/bd/user_35t/ip/user_35t_auto_us_3/user_35t_auto_us_3.xci
# IP: The module: 'user_35t_auto_us_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ilpes/Desktop/INSEGNAMENTO/Didattica2023/McDMA/McDMA_v5_int_edge/McDMA_v5_int_edge.srcs/sources_1/bd/user_35t/ip/user_35t_auto_us_3/user_35t_auto_us_3_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'user_35t_auto_us_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ilpes/Desktop/INSEGNAMENTO/Didattica2023/McDMA/McDMA_v5_int_edge/McDMA_v5_int_edge.srcs/sources_1/bd/user_35t/ip/user_35t_auto_us_3/user_35t_auto_us_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'user_35t_auto_us_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
