# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ilpes/Desktop/Didattica2022/project_8_randomsequenceVHDL/project_8_randomsequenceVHDL.srcs/sources_1/ip/Hit_poisson_Mu30/Hit_poisson_Mu30.xci
# IP: The module: 'Hit_poisson_Mu30' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ilpes/Desktop/Didattica2022/project_8_randomsequenceVHDL/project_8_randomsequenceVHDL.gen/sources_1/ip/Hit_poisson_Mu30/Hit_poisson_Mu30_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Hit_poisson_Mu30'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/ilpes/Desktop/Didattica2022/project_8_randomsequenceVHDL/project_8_randomsequenceVHDL.srcs/sources_1/ip/Hit_poisson_Mu30/Hit_poisson_Mu30.xci
# IP: The module: 'Hit_poisson_Mu30' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ilpes/Desktop/Didattica2022/project_8_randomsequenceVHDL/project_8_randomsequenceVHDL.gen/sources_1/ip/Hit_poisson_Mu30/Hit_poisson_Mu30_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Hit_poisson_Mu30'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
