# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/ilpes/Downloads/project_CMOD_emc_golden_uart/project_MMCM_IIC_noor/project_MMCM_IIC_noor.srcs/sources_1/bd/user_35t/ip/user_35t_m00_data_fifo_0/user_35t_m00_data_fifo_0.xci
# IP: The module: 'user_35t_m00_data_fifo_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ilpes/Downloads/project_CMOD_emc_golden_uart/project_MMCM_IIC_noor/project_MMCM_IIC_noor.srcs/sources_1/bd/user_35t/ip/user_35t_m00_data_fifo_0/user_35t_m00_data_fifo_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'user_35t_m00_data_fifo_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ilpes/Downloads/project_CMOD_emc_golden_uart/project_MMCM_IIC_noor/project_MMCM_IIC_noor.srcs/sources_1/bd/user_35t/ip/user_35t_m00_data_fifo_0/user_35t_m00_data_fifo_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'user_35t_m00_data_fifo_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/ilpes/Downloads/project_CMOD_emc_golden_uart/project_MMCM_IIC_noor/project_MMCM_IIC_noor.srcs/sources_1/bd/user_35t/ip/user_35t_m00_data_fifo_0/user_35t_m00_data_fifo_0.xci
# IP: The module: 'user_35t_m00_data_fifo_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ilpes/Downloads/project_CMOD_emc_golden_uart/project_MMCM_IIC_noor/project_MMCM_IIC_noor.srcs/sources_1/bd/user_35t/ip/user_35t_m00_data_fifo_0/user_35t_m00_data_fifo_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'user_35t_m00_data_fifo_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ilpes/Downloads/project_CMOD_emc_golden_uart/project_MMCM_IIC_noor/project_MMCM_IIC_noor.srcs/sources_1/bd/user_35t/ip/user_35t_m00_data_fifo_0/user_35t_m00_data_fifo_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'user_35t_m00_data_fifo_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
