webtalk_init -webtalk_dir C:/Users/ilpes/TDC_a35t/TDC_a35t_v5_uart_simulating/TDC_a35t_v5_uart_simulating.sim/sim_1/impl/timing/xsim/xsim.dir/TDCchannel_time_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Feb 19 15:22:17 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211439753_179783142_210770513_162" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1e295a68-03a2-4243-81ab-332a92e09120" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e382d27827854236aaac61c138ed5516" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2803 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "4352982998 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1200.67_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "35324_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1107363072 -regid "211439753_179783142_210770513_162" -xml C:/Users/ilpes/TDC_a35t/TDC_a35t_v5_uart_simulating/TDC_a35t_v5_uart_simulating.sim/sim_1/impl/timing/xsim/xsim.dir/TDCchannel_time_impl/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/ilpes/TDC_a35t/TDC_a35t_v5_uart_simulating/TDC_a35t_v5_uart_simulating.sim/sim_1/impl/timing/xsim/xsim.dir/TDCchannel_time_impl/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/ilpes/TDC_a35t/TDC_a35t_v5_uart_simulating/TDC_a35t_v5_uart_simulating.sim/sim_1/impl/timing/xsim/xsim.dir/TDCchannel_time_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
