# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/ilpes/Desktop/Antenne_e_clocks/project_pasticcio/project_pasticcio.srcs/sources_1/bd/micro_core_v0/ip/micro_core_v0_clk_wiz_1_1/micro_core_v0_clk_wiz_1_1.xci
# IP: The module: 'micro_core_v0_clk_wiz_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ilpes/Desktop/Antenne_e_clocks/project_pasticcio/project_pasticcio.gen/sources_1/bd/micro_core_v0/ip/micro_core_v0_clk_wiz_1_1/micro_core_v0_clk_wiz_1_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_core_v0_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ilpes/Desktop/Antenne_e_clocks/project_pasticcio/project_pasticcio.gen/sources_1/bd/micro_core_v0/ip/micro_core_v0_clk_wiz_1_1/micro_core_v0_clk_wiz_1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_core_v0_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ilpes/Desktop/Antenne_e_clocks/project_pasticcio/project_pasticcio.gen/sources_1/bd/micro_core_v0/ip/micro_core_v0_clk_wiz_1_1/micro_core_v0_clk_wiz_1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_core_v0_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/ilpes/Desktop/Antenne_e_clocks/project_pasticcio/project_pasticcio.srcs/sources_1/bd/micro_core_v0/ip/micro_core_v0_clk_wiz_1_1/micro_core_v0_clk_wiz_1_1.xci
# IP: The module: 'micro_core_v0_clk_wiz_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ilpes/Desktop/Antenne_e_clocks/project_pasticcio/project_pasticcio.gen/sources_1/bd/micro_core_v0/ip/micro_core_v0_clk_wiz_1_1/micro_core_v0_clk_wiz_1_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_core_v0_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ilpes/Desktop/Antenne_e_clocks/project_pasticcio/project_pasticcio.gen/sources_1/bd/micro_core_v0/ip/micro_core_v0_clk_wiz_1_1/micro_core_v0_clk_wiz_1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_core_v0_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ilpes/Desktop/Antenne_e_clocks/project_pasticcio/project_pasticcio.gen/sources_1/bd/micro_core_v0/ip/micro_core_v0_clk_wiz_1_1/micro_core_v0_clk_wiz_1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_core_v0_clk_wiz_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
