# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/example_design/gtwizard_0_gtpe2_exdes.xdc

# IP: ip/gtwizard_0_gtpe2/gtwizard_0_gtpe2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gtwizard_0_gtpe2 || ORIG_REF_NAME==gtwizard_0_gtpe2} -quiet] -quiet
