# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/top.xdc

# IP: ip/pixsimFifo/pixsimFifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pixsimFifo || ORIG_REF_NAME==pixsimFifo} -quiet] -quiet

# IP: ip/clk_generator/clk_generator.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_generator || ORIG_REF_NAME==clk_generator} -quiet] -quiet
