# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Cmod-A7-Master.xdc

# Block Designs: bd/user_35t/user_35t.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t || ORIG_REF_NAME==user_35t} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_axi_emc_0_0/user_35t_axi_emc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_axi_emc_0_0 || ORIG_REF_NAME==user_35t_axi_emc_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_axi_gpio_0_0/user_35t_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_axi_gpio_0_0 || ORIG_REF_NAME==user_35t_axi_gpio_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_axi_intc_0_0/user_35t_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_axi_intc_0_0 || ORIG_REF_NAME==user_35t_axi_intc_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_axi_timer_0_0/user_35t_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_axi_timer_0_0 || ORIG_REF_NAME==user_35t_axi_timer_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_axi_uartlite_0_0/user_35t_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_axi_uartlite_0_0 || ORIG_REF_NAME==user_35t_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_clk_wiz_0_0/user_35t_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_clk_wiz_0_0 || ORIG_REF_NAME==user_35t_clk_wiz_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_mdm_1_0/user_35t_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_mdm_1_0 || ORIG_REF_NAME==user_35t_mdm_1_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_microblaze_0_0/user_35t_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_microblaze_0_0 || ORIG_REF_NAME==user_35t_microblaze_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_rst_clk_wiz_0_100M_0/user_35t_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==user_35t_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_xlconcat_0_0/user_35t_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_xlconcat_0_0 || ORIG_REF_NAME==user_35t_xlconcat_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_dlmb_bram_if_cntlr_0/user_35t_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==user_35t_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_dlmb_v10_0/user_35t_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_dlmb_v10_0 || ORIG_REF_NAME==user_35t_dlmb_v10_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_ilmb_bram_if_cntlr_0/user_35t_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==user_35t_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_ilmb_v10_0/user_35t_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_ilmb_v10_0 || ORIG_REF_NAME==user_35t_ilmb_v10_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_lmb_bram_0/user_35t_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_lmb_bram_0 || ORIG_REF_NAME==user_35t_lmb_bram_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_axi_iic_0_0/user_35t_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_axi_iic_0_0 || ORIG_REF_NAME==user_35t_axi_iic_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_axi_quad_spi_0_0/user_35t_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_axi_quad_spi_0_0 || ORIG_REF_NAME==user_35t_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_xadc_wiz_0_0/user_35t_xadc_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_xadc_wiz_0_0 || ORIG_REF_NAME==user_35t_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_axi_dma_0_0/user_35t_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_axi_dma_0_0 || ORIG_REF_NAME==user_35t_axi_dma_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_axi_gpio_0_1/user_35t_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_axi_gpio_0_1 || ORIG_REF_NAME==user_35t_axi_gpio_0_1} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_xlslice_0_0/user_35t_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_xlslice_0_0 || ORIG_REF_NAME==user_35t_xlslice_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_xlslice_0_1/user_35t_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_xlslice_0_1 || ORIG_REF_NAME==user_35t_xlslice_0_1} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_xlconstant_0_0/user_35t_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_xlconstant_0_0 || ORIG_REF_NAME==user_35t_xlconstant_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_xlslice_1_0/user_35t_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_xlslice_1_0 || ORIG_REF_NAME==user_35t_xlslice_1_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_axis_combiner_0_0/user_35t_axis_combiner_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_axis_combiner_0_0 || ORIG_REF_NAME==user_35t_axis_combiner_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_c_counter_binary_0_1/user_35t_c_counter_binary_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_c_counter_binary_0_1 || ORIG_REF_NAME==user_35t_c_counter_binary_0_1} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_stream_tlaster_0_2/user_35t_stream_tlaster_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_stream_tlaster_0_2 || ORIG_REF_NAME==user_35t_stream_tlaster_0_2} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_c0_0/user_35t_c0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_c0_0 || ORIG_REF_NAME==user_35t_c0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_streamer_c0_0/user_35t_streamer_c0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_streamer_c0_0 || ORIG_REF_NAME==user_35t_streamer_c0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_c0_1/user_35t_c0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_c0_1 || ORIG_REF_NAME==user_35t_c0_1} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_streamer_c0_1/user_35t_streamer_c0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_streamer_c0_1 || ORIG_REF_NAME==user_35t_streamer_c0_1} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_c0_2/user_35t_c0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_c0_2 || ORIG_REF_NAME==user_35t_c0_2} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_streamer_c0_2/user_35t_streamer_c0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_streamer_c0_2 || ORIG_REF_NAME==user_35t_streamer_c0_2} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_c0_4/user_35t_c0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_c0_4 || ORIG_REF_NAME==user_35t_c0_4} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_streamer_c0_4/user_35t_streamer_c0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_streamer_c0_4 || ORIG_REF_NAME==user_35t_streamer_c0_4} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_c0_5/user_35t_c0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_c0_5 || ORIG_REF_NAME==user_35t_c0_5} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_streamer_c0_5/user_35t_streamer_c0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_streamer_c0_5 || ORIG_REF_NAME==user_35t_streamer_c0_5} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_c0_6/user_35t_c0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_c0_6 || ORIG_REF_NAME==user_35t_c0_6} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_streamer_c0_6/user_35t_streamer_c0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_streamer_c0_6 || ORIG_REF_NAME==user_35t_streamer_c0_6} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_c0_7/user_35t_c0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_c0_7 || ORIG_REF_NAME==user_35t_c0_7} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_streamer_c0_7/user_35t_streamer_c0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_streamer_c0_7 || ORIG_REF_NAME==user_35t_streamer_c0_7} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_c0_9/user_35t_c0_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_c0_9 || ORIG_REF_NAME==user_35t_c0_9} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_streamer_c0_9/user_35t_streamer_c0_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_streamer_c0_9 || ORIG_REF_NAME==user_35t_streamer_c0_9} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_c0_10/user_35t_c0_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_c0_10 || ORIG_REF_NAME==user_35t_c0_10} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_streamer_c0_10/user_35t_streamer_c0_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_streamer_c0_10 || ORIG_REF_NAME==user_35t_streamer_c0_10} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_c0_11/user_35t_c0_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_c0_11 || ORIG_REF_NAME==user_35t_c0_11} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_streamer_c0_11/user_35t_streamer_c0_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_streamer_c0_11 || ORIG_REF_NAME==user_35t_streamer_c0_11} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_c0_12/user_35t_c0_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_c0_12 || ORIG_REF_NAME==user_35t_c0_12} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_streamer_c0_12/user_35t_streamer_c0_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_streamer_c0_12 || ORIG_REF_NAME==user_35t_streamer_c0_12} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_c0_13/user_35t_c0_13.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_c0_13 || ORIG_REF_NAME==user_35t_c0_13} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_streamer_c0_13/user_35t_streamer_c0_13.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_streamer_c0_13 || ORIG_REF_NAME==user_35t_streamer_c0_13} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_c0_14/user_35t_c0_14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_c0_14 || ORIG_REF_NAME==user_35t_c0_14} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_streamer_c0_14/user_35t_streamer_c0_14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_streamer_c0_14 || ORIG_REF_NAME==user_35t_streamer_c0_14} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_c0_3/user_35t_c0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_c0_3 || ORIG_REF_NAME==user_35t_c0_3} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_streamer_c0_3/user_35t_streamer_c0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_streamer_c0_3 || ORIG_REF_NAME==user_35t_streamer_c0_3} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_axi_dma_0_1/user_35t_axi_dma_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_axi_dma_0_1 || ORIG_REF_NAME==user_35t_axi_dma_0_1} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_ila_0_0/user_35t_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_ila_0_0 || ORIG_REF_NAME==user_35t_ila_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_ila_combiner_1/user_35t_ila_combiner_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_ila_combiner_1 || ORIG_REF_NAME==user_35t_ila_combiner_1} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_init_counters_0/user_35t_init_counters_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_init_counters_0 || ORIG_REF_NAME==user_35t_init_counters_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_xbar_4/user_35t_xbar_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_xbar_4 || ORIG_REF_NAME==user_35t_xbar_4} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_axi_interconnect_0_0/user_35t_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_axi_interconnect_0_0 || ORIG_REF_NAME==user_35t_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_xbar_5/user_35t_xbar_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_xbar_5 || ORIG_REF_NAME==user_35t_xbar_5} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_axi_interconnect_1_0/user_35t_axi_interconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_axi_interconnect_1_0 || ORIG_REF_NAME==user_35t_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_ila_ch0_0/user_35t_ila_ch0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_ila_ch0_0 || ORIG_REF_NAME==user_35t_ila_ch0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_ila_TF_0/user_35t_ila_TF_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_ila_TF_0 || ORIG_REF_NAME==user_35t_ila_TF_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_axis_data_fifo_0_0/user_35t_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_axis_data_fifo_0_0 || ORIG_REF_NAME==user_35t_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_axi_gpio_1_0/user_35t_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_axi_gpio_1_0 || ORIG_REF_NAME==user_35t_axi_gpio_1_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_c_counter_binary_0_2/user_35t_c_counter_binary_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_c_counter_binary_0_2 || ORIG_REF_NAME==user_35t_c_counter_binary_0_2} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_util_vector_logic_0_0/user_35t_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_util_vector_logic_0_0 || ORIG_REF_NAME==user_35t_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_xlslice_0_2/user_35t_xlslice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_xlslice_0_2 || ORIG_REF_NAME==user_35t_xlslice_0_2} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_xlslice_0_3/user_35t_xlslice_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_xlslice_0_3 || ORIG_REF_NAME==user_35t_xlslice_0_3} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_axis_data_fifo_0_2/user_35t_axis_data_fifo_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_axis_data_fifo_0_2 || ORIG_REF_NAME==user_35t_axis_data_fifo_0_2} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_axi_dma_0_2/user_35t_axi_dma_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_axi_dma_0_2 || ORIG_REF_NAME==user_35t_axi_dma_0_2} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_auto_us_0/user_35t_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_auto_us_0 || ORIG_REF_NAME==user_35t_auto_us_0} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_auto_us_1/user_35t_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_auto_us_1 || ORIG_REF_NAME==user_35t_auto_us_1} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_auto_us_2/user_35t_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_auto_us_2 || ORIG_REF_NAME==user_35t_auto_us_2} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_auto_us_3/user_35t_auto_us_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_auto_us_3 || ORIG_REF_NAME==user_35t_auto_us_3} -quiet] -quiet

# IP: bd/user_35t/ip/user_35t_auto_ds_0/user_35t_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==user_35t_auto_ds_0 || ORIG_REF_NAME==user_35t_auto_ds_0} -quiet] -quiet

# XDC: bd/user_35t/user_35t_ooc.xdc
