# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ilpes/Desktop/Antenne_e_clocks/project_MicroBlaze_simple/project_MicroBlaze_simple.srcs/sources_1/bd/micro_core_v0/ip/micro_core_v0_dlmb_v10_2/micro_core_v0_dlmb_v10_2.xci
# IP: The module: 'micro_core_v0_dlmb_v10_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ilpes/Desktop/Antenne_e_clocks/project_MicroBlaze_simple/project_MicroBlaze_simple.gen/sources_1/bd/micro_core_v0/ip/micro_core_v0_dlmb_v10_2/micro_core_v0_dlmb_v10_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_core_v0_dlmb_v10_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/ilpes/Desktop/Antenne_e_clocks/project_MicroBlaze_simple/project_MicroBlaze_simple.srcs/sources_1/bd/micro_core_v0/ip/micro_core_v0_dlmb_v10_2/micro_core_v0_dlmb_v10_2.xci
# IP: The module: 'micro_core_v0_dlmb_v10_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ilpes/Desktop/Antenne_e_clocks/project_MicroBlaze_simple/project_MicroBlaze_simple.gen/sources_1/bd/micro_core_v0/ip/micro_core_v0_dlmb_v10_2/micro_core_v0_dlmb_v10_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_core_v0_dlmb_v10_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
