# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ilpes/Desktop/Antenne_e_clocks/project_pasticcio/project_pasticcio.srcs/sources_1/bd/micro_core_v0/ip/micro_core_v0_mdm_1_7/micro_core_v0_mdm_1_7.xci
# IP: The module: 'micro_core_v0_mdm_1_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ilpes/Desktop/Antenne_e_clocks/project_pasticcio/project_pasticcio.gen/sources_1/bd/micro_core_v0/ip/micro_core_v0_mdm_1_7/micro_core_v0_mdm_1_7.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_core_v0_mdm_1_7'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ilpes/Desktop/Antenne_e_clocks/project_pasticcio/project_pasticcio.gen/sources_1/bd/micro_core_v0/ip/micro_core_v0_mdm_1_7/micro_core_v0_mdm_1_7_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_core_v0_mdm_1_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/ilpes/Desktop/Antenne_e_clocks/project_pasticcio/project_pasticcio.srcs/sources_1/bd/micro_core_v0/ip/micro_core_v0_mdm_1_7/micro_core_v0_mdm_1_7.xci
# IP: The module: 'micro_core_v0_mdm_1_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ilpes/Desktop/Antenne_e_clocks/project_pasticcio/project_pasticcio.gen/sources_1/bd/micro_core_v0/ip/micro_core_v0_mdm_1_7/micro_core_v0_mdm_1_7.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_core_v0_mdm_1_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ilpes/Desktop/Antenne_e_clocks/project_pasticcio/project_pasticcio.gen/sources_1/bd/micro_core_v0/ip/micro_core_v0_mdm_1_7/micro_core_v0_mdm_1_7_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_core_v0_mdm_1_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
