# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/ilpes/Desktop/Antenne_e_clocks/project_pasticcio/project_pasticcio.srcs/sources_1/bd/micro_core_v0/ip/micro_core_v0_microblaze_0_6/micro_core_v0_microblaze_0_6.xci
# IP: The module: 'micro_core_v0_microblaze_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ilpes/Desktop/Antenne_e_clocks/project_pasticcio/project_pasticcio.gen/sources_1/bd/micro_core_v0/ip/micro_core_v0_microblaze_0_6/micro_core_v0_microblaze_0_6.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_core_v0_microblaze_0_6'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ilpes/Desktop/Antenne_e_clocks/project_pasticcio/project_pasticcio.gen/sources_1/bd/micro_core_v0/ip/micro_core_v0_microblaze_0_6/micro_core_v0_microblaze_0_6_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_core_v0_microblaze_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ilpes/Desktop/Antenne_e_clocks/project_pasticcio/project_pasticcio.gen/sources_1/bd/micro_core_v0/ip/micro_core_v0_microblaze_0_6/micro_core_v0_microblaze_0_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_core_v0_microblaze_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/ilpes/Desktop/Antenne_e_clocks/project_pasticcio/project_pasticcio.srcs/sources_1/bd/micro_core_v0/ip/micro_core_v0_microblaze_0_6/micro_core_v0_microblaze_0_6.xci
# IP: The module: 'micro_core_v0_microblaze_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ilpes/Desktop/Antenne_e_clocks/project_pasticcio/project_pasticcio.gen/sources_1/bd/micro_core_v0/ip/micro_core_v0_microblaze_0_6/micro_core_v0_microblaze_0_6.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_core_v0_microblaze_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ilpes/Desktop/Antenne_e_clocks/project_pasticcio/project_pasticcio.gen/sources_1/bd/micro_core_v0/ip/micro_core_v0_microblaze_0_6/micro_core_v0_microblaze_0_6_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_core_v0_microblaze_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ilpes/Desktop/Antenne_e_clocks/project_pasticcio/project_pasticcio.gen/sources_1/bd/micro_core_v0/ip/micro_core_v0_microblaze_0_6/micro_core_v0_microblaze_0_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'micro_core_v0_microblaze_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
