@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Feb 20 13:26:52 +0100 2026
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim TDCchannel_time_impl -key {Post-Implementation:sim_1:Timing:TDCchannel} -tclbatch TDCchannel.tcl -view C:/Users/ilpes/TDC_a35t/TDC_a35t_v7_noFFHit/TDC_a35t_v7_noFFHit.srcs/sim_1/imports/TDC_a35t_v4_uart/TDCchannel_time_impl.wcfg -view C:/Users/ilpes/TDC_a35t/TDC_a35t_v7_noFFHit/TDC_a35t_v7_noFFHit.srcs/sim_1/imports/TDC_a35t_v4_uart/TDCchannel_behav.wcfg -log simulate.log"
call xsim  TDCchannel_time_impl -key {Post-Implementation:sim_1:Timing:TDCchannel} -tclbatch TDCchannel.tcl -view C:/Users/ilpes/TDC_a35t/TDC_a35t_v7_noFFHit/TDC_a35t_v7_noFFHit.srcs/sim_1/imports/TDC_a35t_v4_uart/TDCchannel_time_impl.wcfg -view C:/Users/ilpes/TDC_a35t/TDC_a35t_v7_noFFHit/TDC_a35t_v7_noFFHit.srcs/sim_1/imports/TDC_a35t_v4_uart/TDCchannel_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
