# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constrs_1/imports/new/top.xdc

# Block Designs: bd/micro_core_v0/micro_core_v0.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0 || ORIG_REF_NAME==micro_core_v0} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_axi_uartlite_0_0/micro_core_v0_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_axi_uartlite_0_0 || ORIG_REF_NAME==micro_core_v0_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_microblaze_0_1/micro_core_v0_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_microblaze_0_1 || ORIG_REF_NAME==micro_core_v0_microblaze_0_1} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_dlmb_v10_2/micro_core_v0_dlmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_dlmb_v10_2 || ORIG_REF_NAME==micro_core_v0_dlmb_v10_2} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_ilmb_v10_2/micro_core_v0_ilmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_ilmb_v10_2 || ORIG_REF_NAME==micro_core_v0_ilmb_v10_2} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_dlmb_bram_if_cntlr_2/micro_core_v0_dlmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==micro_core_v0_dlmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_ilmb_bram_if_cntlr_2/micro_core_v0_ilmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==micro_core_v0_ilmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_lmb_bram_2/micro_core_v0_lmb_bram_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_lmb_bram_2 || ORIG_REF_NAME==micro_core_v0_lmb_bram_2} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_mdm_1_1/micro_core_v0_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_mdm_1_1 || ORIG_REF_NAME==micro_core_v0_mdm_1_1} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_rst_sys_clock_12M_0/micro_core_v0_rst_sys_clock_12M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_rst_sys_clock_12M_0 || ORIG_REF_NAME==micro_core_v0_rst_sys_clock_12M_0} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_microblaze_0_axi_periph_1/micro_core_v0_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_microblaze_0_axi_periph_1 || ORIG_REF_NAME==micro_core_v0_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_xbar_0/micro_core_v0_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_xbar_0 || ORIG_REF_NAME==micro_core_v0_xbar_0} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_clk_wiz_0_0/micro_core_v0_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_clk_wiz_0_0 || ORIG_REF_NAME==micro_core_v0_clk_wiz_0_0} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_axi_gpio_0_0/micro_core_v0_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_axi_gpio_0_0 || ORIG_REF_NAME==micro_core_v0_axi_gpio_0_0} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_xlslice_0_0/micro_core_v0_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_xlslice_0_0 || ORIG_REF_NAME==micro_core_v0_xlslice_0_0} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_xlslice_1_0/micro_core_v0_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_xlslice_1_0 || ORIG_REF_NAME==micro_core_v0_xlslice_1_0} -quiet] -quiet

# XDC: C:/Users/ilpes/Desktop/Antenne_e_clocks/project_MicroBlaze_simple/project_MicroBlaze_simple.gen/sources_1/bd/micro_core_v0/micro_core_v0_ooc.xdc
