# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ilpes/TDC_a35t/TDC_a35t_v3/TDC_a35t_v3.srcs/sources_1/ip/PLL_A/PLL_A.xci
# IP: The module: 'PLL_A' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ilpes/TDC_a35t/TDC_a35t_v3/TDC_a35t_v3.gen/sources_1/ip/PLL_A/PLL_A_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_A'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ilpes/TDC_a35t/TDC_a35t_v3/TDC_a35t_v3.gen/sources_1/ip/PLL_A/PLL_A.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_A'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ilpes/TDC_a35t/TDC_a35t_v3/TDC_a35t_v3.gen/sources_1/ip/PLL_A/PLL_A_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_A'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/ilpes/TDC_a35t/TDC_a35t_v3/TDC_a35t_v3.srcs/sources_1/ip/PLL_A/PLL_A.xci
# IP: The module: 'PLL_A' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ilpes/TDC_a35t/TDC_a35t_v3/TDC_a35t_v3.gen/sources_1/ip/PLL_A/PLL_A_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_A'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ilpes/TDC_a35t/TDC_a35t_v3/TDC_a35t_v3.gen/sources_1/ip/PLL_A/PLL_A.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_A'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ilpes/TDC_a35t/TDC_a35t_v3/TDC_a35t_v3.gen/sources_1/ip/PLL_A/PLL_A_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_A'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
