# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constrs_1/imports/new/top.xdc

# Block Designs: bd/micro_core_v0/micro_core_v0.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0 || ORIG_REF_NAME==micro_core_v0} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_axi_uartlite_0_0/micro_core_v0_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_axi_uartlite_0_0 || ORIG_REF_NAME==micro_core_v0_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_clk_wiz_0_0/micro_core_v0_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_clk_wiz_0_0 || ORIG_REF_NAME==micro_core_v0_clk_wiz_0_0} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_axi_gpio_0_0/micro_core_v0_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_axi_gpio_0_0 || ORIG_REF_NAME==micro_core_v0_axi_gpio_0_0} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_xlslice_0_0/micro_core_v0_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_xlslice_0_0 || ORIG_REF_NAME==micro_core_v0_xlslice_0_0} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_xlslice_1_0/micro_core_v0_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_xlslice_1_0 || ORIG_REF_NAME==micro_core_v0_xlslice_1_0} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_axi_intc_0_0/micro_core_v0_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_axi_intc_0_0 || ORIG_REF_NAME==micro_core_v0_axi_intc_0_0} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_axi_emc_0_0/micro_core_v0_axi_emc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_axi_emc_0_0 || ORIG_REF_NAME==micro_core_v0_axi_emc_0_0} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_xlslice_2_0/micro_core_v0_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_xlslice_2_0 || ORIG_REF_NAME==micro_core_v0_xlslice_2_0} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_clk_wiz_1_1/micro_core_v0_clk_wiz_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_clk_wiz_1_1 || ORIG_REF_NAME==micro_core_v0_clk_wiz_1_1} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_microblaze_0_6/micro_core_v0_microblaze_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_microblaze_0_6 || ORIG_REF_NAME==micro_core_v0_microblaze_0_6} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_dlmb_v10_8/micro_core_v0_dlmb_v10_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_dlmb_v10_8 || ORIG_REF_NAME==micro_core_v0_dlmb_v10_8} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_ilmb_v10_8/micro_core_v0_ilmb_v10_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_ilmb_v10_8 || ORIG_REF_NAME==micro_core_v0_ilmb_v10_8} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_dlmb_bram_if_cntlr_8/micro_core_v0_dlmb_bram_if_cntlr_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_dlmb_bram_if_cntlr_8 || ORIG_REF_NAME==micro_core_v0_dlmb_bram_if_cntlr_8} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_ilmb_bram_if_cntlr_8/micro_core_v0_ilmb_bram_if_cntlr_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_ilmb_bram_if_cntlr_8 || ORIG_REF_NAME==micro_core_v0_ilmb_bram_if_cntlr_8} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_lmb_bram_8/micro_core_v0_lmb_bram_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_lmb_bram_8 || ORIG_REF_NAME==micro_core_v0_lmb_bram_8} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_mdm_1_7/micro_core_v0_mdm_1_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_mdm_1_7 || ORIG_REF_NAME==micro_core_v0_mdm_1_7} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_rst_clk_wiz_1_100M_3/micro_core_v0_rst_clk_wiz_1_100M_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_rst_clk_wiz_1_100M_3 || ORIG_REF_NAME==micro_core_v0_rst_clk_wiz_1_100M_3} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_axi_smc_0/micro_core_v0_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_axi_smc_0 || ORIG_REF_NAME==micro_core_v0_axi_smc_0} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_xbar_4/micro_core_v0_xbar_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_xbar_4 || ORIG_REF_NAME==micro_core_v0_xbar_4} -quiet] -quiet

# IP: bd/micro_core_v0/ip/micro_core_v0_microblaze_0_axi_periph_5/micro_core_v0_microblaze_0_axi_periph_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==micro_core_v0_microblaze_0_axi_periph_5 || ORIG_REF_NAME==micro_core_v0_microblaze_0_axi_periph_5} -quiet] -quiet

# XDC: c:/Users/ilpes/Desktop/Antenne_e_clocks/project_pasticcio/project_pasticcio.gen/sources_1/bd/micro_core_v0/micro_core_v0_ooc.xdc
