# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Cmod-A7-Master.xdc

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: ip/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_bram_ctrl_0 || ORIG_REF_NAME==axi_bram_ctrl_0} -quiet] -quiet

# IP: ip/axi_gpio_0/axi_gpio_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_0 || ORIG_REF_NAME==axi_gpio_0} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# XDC: c:/Users/ilpes/TDC_a35t/TDC_a35t_v1/TDC_a35t_v0.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: c:/Users/ilpes/TDC_a35t/TDC_a35t_v1/TDC_a35t_v0.gen/sources_1/ip/axi_gpio_0/axi_gpio_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_gpio_0 || ORIG_REF_NAME==axi_gpio_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/ilpes/TDC_a35t/TDC_a35t_v1/TDC_a35t_v0.gen/sources_1/ip/axi_gpio_0/axi_gpio_0_ooc.xdc

# XDC: c:/Users/ilpes/TDC_a35t/TDC_a35t_v1/TDC_a35t_v0.gen/sources_1/ip/axi_gpio_0/axi_gpio_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_gpio_0 || ORIG_REF_NAME==axi_gpio_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
